### ISSUE TITLE
addColorbarNonImage changes the parent axis

### ISSUE THREAD

**Issue by cpbl** [cpbl/cpblUtilities#6] opened 2017-09-19 19:59 UTC
add preserve_axis_position=True
   This should restore the parent axis position, and move the colorbar back to the edge of the parent axis after restoring the former.

Also restore the xlims!

**Comment by amillb** [comment] 2017-09-20 00:00
Still not working as intended (it did for a while, then I think the last commit reverted it). The xaxis is restored as intended, but the colorbar doesn't move with it. See Montreal.tiff in `tmpgraphics`.

One issue: should
```
cbax_position.x0 = cbax_position.x0 + parent_axis_position.x1 - revised_parent_position.x1
```
be 
```
cbax_position.x0 = cbax_position.x0 + parent_axis_position.x0 - revised_parent_position.x
```

Or maybe the plt.draw() is messing things up?

**Comment by cpbl** [comment] 2017-09-20 00:02
What the heck? That's not the latest commit. There must have been a reversion somehow.

**Comment by cpbl** [comment] 2017-09-20 00:03
I will look into it. Have you done any manual merges recently? Very odd.

**Comment by amillb** [comment] 2017-09-20 00:05
No, I haven't merged anything into cpblUtilities, as far as I know.

**Comment by cpbl** [comment] 2017-09-20 00:08
If you try `run osmTools' (or `python osmTools.py`)  does it look good?

**Closed** 2017-09-20 00:14 UTC

**Comment by amillb** [comment] 2017-09-20 00:40
The first plot in `osmTools` looks good.

Then it exits with `NameError: global name 'debug' is not defined`

**Comment by cpbl** [comment] 2017-09-20 00:48
Sorry. That's fixed.

**Comment by cpbl** [comment] 2018-02-25 06:01
Commit https://github.com/cpbl/cpblUtilities/commit/503fd1d6de841c2ab2b8e85e596b4ac4fa6c7c7d is in error in referencing #6. It was #6 in pystata repo.
